const KEY = 'coursework-planner-v1';
let courses = readData();
let editingCourse = null;
let editingAssignment = null;
const $ = (id) => document.getElementById(id);
const colors = ['coral', 'teal', 'gold', 'blue'];
function readData() { try { return JSON.parse(localStorage.getItem(KEY)) || []; } catch { return []; } }
function saveData() { localStorage.setItem(KEY, JSON.stringify(courses)); $('saveState').textContent = '● Saved locally'; $('updatedAt').textContent = `Updated just now · ${new Date().toLocaleTimeString([], {hour:'numeric', minute:'2-digit'})}`; }
function makeId() { return Date.now().toString(36) + Math.random().toString(36).slice(2); }
function clean(value) { return String(value).replace(/[&<>'"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function dueDate(date) { return new Date(`${date}T12:00:00`).toLocaleDateString([], {month:'short', day:'numeric'}); }
function allAssignments() { return courses.flatMap((course) => course.assignments.map((assignment) => ({...assignment, course}))); }
function toast(message) { const element = $('toast'); element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 2200); }
function render() {
  const assignments = allAssignments(); const completed = assignments.filter((item) => item.complete).length; const percent = assignments.length ? Math.round(completed / assignments.length * 100) : 0;
  $('courseCount').textContent = courses.length; $('openCount').textContent = assignments.length - completed; $('completedCount').textContent = completed; $('overallProgress').textContent = `${percent}%`; $('overallBar').style.width = `${percent}%`;
  $('progressFoot').textContent = assignments.length ? `${completed} of ${assignments.length} assignments complete` : "Let's get started";
  const next = assignments.filter((item) => !item.complete).sort((a,b) => a.due.localeCompare(b.due))[0]; $('nextUp').textContent = next ? next.name : 'No deadlines yet'; $('nextUpMeta').textContent = next ? `${next.course.code || next.course.name} · due ${dueDate(next.due)}` : 'Add an assignment to get started'; $('dueSoon').textContent = next ? `Next: ${dueDate(next.due)}` : 'Nothing due soon';
  $('emptyState').hidden = courses.length > 0; $('courseList').innerHTML = courses.map(courseMarkup).join('');
}
function courseMarkup(course) { const finished = course.assignments.filter((item) => item.complete).length; const rows = course.assignments.length ? `<ul class="assignment-list">${course.assignments.map((item) => assignmentMarkup(course.id, item)).join('')}</ul>` : '<div class="no-assignments">No assignments yet. Add the first one below.</div>'; return `<article class="course-card ${course.color}"><div class="course-head"><div><h3>${clean(course.name)}</h3><span class="course-code">${clean(course.code || 'Course')} · ${finished}/${course.assignments.length} complete</span></div><div class="course-actions"><select class="priority-select" aria-label="Course priority" onchange="setCoursePriority('${course.id}', this.value)"><option value="high" ${course.priority==='high'?'selected':''}>High priority</option><option value="medium" ${course.priority==='medium'?'selected':''}>Medium priority</option><option value="low" ${course.priority==='low'?'selected':''}>Low priority</option></select><button class="icon-button" onclick="editCourse('${course.id}')" aria-label="Edit course">✎</button><button class="icon-button" onclick="removeCourse('${course.id}')" aria-label="Delete course">×</button></div></div>${rows}<div class="course-footer"><button class="link-button" onclick="editAssignment('${course.id}')">＋ Add assignment</button></div></article>`; }
function assignmentMarkup(courseId, item) { return `<li class="assignment-row"><button class="check ${item.complete?'done':''}" onclick="toggleAssignment('${courseId}','${item.id}')" aria-label="Toggle completion"></button><span class="assignment-name ${item.complete?'done':''}">${clean(item.name)}</span><span class="due">Due ${dueDate(item.due)}</span><select class="priority-select priority ${item.priority}" aria-label="Assignment priority" onchange="setAssignmentPriority('${courseId}','${item.id}',this.value)"><option value="high" ${item.priority==='high'?'selected':''}>High</option><option value="medium" ${item.priority==='medium'?'selected':''}>Medium</option><option value="low" ${item.priority==='low'?'selected':''}>Low</option></select><span class="row-actions"><button onclick="editAssignment('${courseId}','${item.id}')" aria-label="Edit assignment">✎</button><button onclick="removeAssignment('${courseId}','${item.id}')" aria-label="Delete assignment">×</button></span></li>`; }
function openCourse(courseId) { editingCourse = courseId; const course = courses.find((item) => item.id === courseId); $('courseDialogTitle').textContent = course ? 'Edit course' : 'Add a course'; $('courseName').value = course?.name || ''; $('courseCode').value = course?.code || ''; $('courseColor').value = course?.color || colors[courses.length % colors.length]; $('courseDialog').showModal(); $('courseName').focus(); }
function editCourse(courseId) { openCourse(courseId); }
function openAssignment(courseId, assignmentId) { const course = courses.find((item) => item.id === courseId); const item = course.assignments.find((assignment) => assignment.id === assignmentId); editingAssignment = {courseId, assignmentId}; $('assignmentDialogTitle').textContent = item ? 'Edit assignment' : `Add to ${course.name}`; $('assignmentName').value = item?.name || ''; $('assignmentDue').value = item?.due || new Date().toISOString().slice(0,10); $('assignmentPriority').value = item?.priority || 'medium'; $('assignmentDialog').showModal(); $('assignmentName').focus(); }
function editAssignment(courseId, assignmentId = null) { openAssignment(courseId, assignmentId); }
$('addCourse').onclick = () => openCourse(null); $('addFirst').onclick = () => openCourse(null);
$('courseForm').onsubmit = (event) => { event.preventDefault(); const course = courses.find((item) => item.id === editingCourse); const data = {name:$('courseName').value.trim(),code:$('courseCode').value.trim(),color:$('courseColor').value}; if (course) { Object.assign(course, data); toast('Course updated'); } else { courses.push({...data, id:makeId(), priority:'medium', assignments:[]}); toast('Course added'); } saveData(); render(); $('courseDialog').close(); };
$('assignmentForm').onsubmit = (event) => { event.preventDefault(); const course = courses.find((item) => item.id === editingAssignment.courseId); const data = {name:$('assignmentName').value.trim(),due:$('assignmentDue').value,priority:$('assignmentPriority').value}; const item = course.assignments.find((assignment) => assignment.id === editingAssignment.assignmentId); if (item) { Object.assign(item, data); toast('Assignment updated'); } else { course.assignments.push({...data,id:makeId(),complete:false}); toast('Assignment added'); } saveData(); render(); $('assignmentDialog').close(); };
function removeCourse(id) { if (!confirm('Delete this course and all its assignments?')) return; courses = courses.filter((course) => course.id !== id); saveData(); render(); toast('Course deleted'); }
function removeAssignment(courseId, assignmentId) { if (!confirm('Delete this assignment?')) return; const course = courses.find((item) => item.id === courseId); course.assignments = course.assignments.filter((item) => item.id !== assignmentId); saveData(); render(); toast('Assignment deleted'); }
function toggleAssignment(courseId, assignmentId) { const item = courses.find((course) => course.id === courseId).assignments.find((assignment) => assignment.id === assignmentId); item.complete = !item.complete; saveData(); render(); }
function setCoursePriority(id, priority) { courses.find((course) => course.id === id).priority = priority; saveData(); toast('Course priority updated'); }
function setAssignmentPriority(courseId, assignmentId, priority) { const item = courses.find((course) => course.id === courseId).assignments.find((assignment) => assignment.id === assignmentId); item.priority = priority; saveData(); toast('Assignment priority updated'); }
document.querySelectorAll('[data-close]').forEach((button) => button.onclick = () => $(button.dataset.close).close());
render();
